//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaterijeKaveza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaterijeKaveza()
        {
            this.UnosUginulih = new HashSet<UnosUginulih>();
            this.KokosiTurnus = new HashSet<KokosiTurnus>();
        }
    
        public int idBaterije { get; set; }
        public int brojKokosi { get; set; }
        public int brojKavezaBaterije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnosUginulih> UnosUginulih { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KokosiTurnus> KokosiTurnus { get; set; }
    }
}
