//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChickenCheckEntiteti : DbContext
    {
        public ChickenCheckEntiteti()
            : base("name=ChickenCheckEntiteti")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AzuriranjeSirovina> AzuriranjeSirovina { get; set; }
        public virtual DbSet<BaterijeKaveza> BaterijeKaveza { get; set; }
        public virtual DbSet<Cijepljenje> Cijepljenje { get; set; }
        public virtual DbSet<Cjepivo> Cjepivo { get; set; }
        public virtual DbSet<Funkcionalnost> Funkcionalnost { get; set; }
        public virtual DbSet<Jaja> Jaja { get; set; }
        public virtual DbSet<KokosiTurnus> KokosiTurnus { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Kupac> Kupac { get; set; }
        public virtual DbSet<LogAkcija> LogAkcija { get; set; }
        public virtual DbSet<Narudzba> Narudzba { get; set; }
        public virtual DbSet<Recept> Recept { get; set; }
        public virtual DbSet<Sirovina> Sirovina { get; set; }
        public virtual DbSet<StanjeNarudzbe> StanjeNarudzbe { get; set; }
        public virtual DbSet<StavkeNarudzbe> StavkeNarudzbe { get; set; }
        public virtual DbSet<UnositeljJaja> UnositeljJaja { get; set; }
        public virtual DbSet<UnosUginulih> UnosUginulih { get; set; }
    }
}
