//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cijepljenje
    {
        public int turnusId { get; set; }
        public int cijepivoId { get; set; }
        public System.DateTime datumCijepljenja { get; set; }
    
        public virtual Cjepivo Cjepivo { get; set; }
        public virtual KokosiTurnus KokosiTurnus { get; set; }
    }
}
