//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjepivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cjepivo()
        {
            this.Cijepljenje = new HashSet<Cijepljenje>();
        }
    
        public int idCjepiva { get; set; }
        public string nazivCjepiva { get; set; }
        public string vrstaCjepiva { get; set; }
        public string opis { get; set; }
        public bool zapisNeaktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cijepljenje> Cijepljenje { get; set; }
    }
}
