//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recept
    {
        public int receptGlavniSastojakId { get; set; }
        public int receptSastojak { get; set; }
        public decimal postotak { get; set; }
    
        public virtual Sirovina Sirovina { get; set; }
        public virtual Sirovina Sirovina1 { get; set; }
    }
}
