//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkeNarudzbe
    {
        public int idStavke { get; set; }
        public int kolicina { get; set; }
        public string klasa { get; set; }
        public double cijena { get; set; }
    
        public virtual Narudzba Narudzba { get; set; }
    }
}
