//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnosUginulih
    {
        public int idZapisa { get; set; }
        public System.DateTime datumUnosa { get; set; }
        public int brojUginulihKokosi { get; set; }
        public string uzrok { get; set; }
    
        public virtual BaterijeKaveza BaterijeKaveza { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
